language: cpp

compiler:
   - gcc
   - clang

install:
   - sudo apt-get update -qq
   - sudo apt-get install -qq libqt4-dev

script:
   - qmake meewod/meewod.pro -r spec default -unix -after "OBJECTS_DIR=obj" "MOC_DIR=moc" "UI_DIR=ui" "RCC_DIR=rcc"
   - make
